image: node:latest

cache:
  paths:
    - node_modules/

test_letslearn:
  script:
    - npm install
    - cd code
    - npm test
# before_script:
#   - apt update
#   - pip3 install -r requirements.txt

# test:
#   script:
#     - python3 -m unittest discover -v