before_script:
    - apt update
    - pip3 install -r requirements.txt

test:1.1:
    image: python
    script:
        - python3 -m unittest discover -v
    
test:1.2:   
    image: node:latest
    cache:
      paths:
        - node_modules/
    script:
        - cd code
        - npm install
        - npm test
        